name: Sync info.json

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest info.json
        id: update
        run: |
          set -euo pipefail
          url="https://carbon.website/carbon/android-resources/dapps/info.json"
          etag_file="info.etag"
          tmp_file="$(mktemp)"
          tmp_headers="$(mktemp)"
          trap 'rm -f "$tmp_file" "$tmp_headers"' EXIT
          curl_args=(-sS -w '%{http_code}' -D "$tmp_headers" -o "$tmp_file" -A "Mozilla/5.0 (compatible; GitHub-Actions-Sync/1.0)")

          old_etag="$(cat "$etag_file" 2>/dev/null || true)"
          if [ -n "$old_etag" ]; then
            status="$(curl "${curl_args[@]}" -H "If-None-Match: $old_etag" "$url")"
          else
            status="$(curl "${curl_args[@]}" "$url")"
          fi

          if [ "$status" = "304" ]; then
            echo "Remote ETag matches local copy. Nothing to update."
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [ "$status" != "200" ] && [ -n "$old_etag" ]; then
            echo "Conditional request returned HTTP $status. Retrying without ETag header."
            : > "$tmp_headers"
            status="$(curl "${curl_args[@]}" "$url")"
          fi

          if [ "$status" != "200" ]; then
            echo "Unexpected HTTP status: $status" >&2
            exit 1
          fi

          new_etag="$(awk 'BEGIN {IGNORECASE=1} /^etag:/ {print $2; exit}' "$tmp_headers" | tr -d '\r')"
          mv "$tmp_file" info.json

          if [ -n "$new_etag" ]; then
            printf '%s\n' "$new_etag" > "$etag_file"
          else
            rm -f "$etag_file"
          fi

          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Commit and push if updated
        if: steps.update.outputs.changed == 'true'
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add info.json info.etag
          git commit -m "Update info.json from carbon website"
          git push
